#!/bin/bash
set -eu

SIGNAL=/data/REPLICATE_THIS
LOG=/data/log

manage_mibios check

sleep 999999
if [[ ! -e $SIGNAL ]]; then
    echo "nothing to do"
    exit 0
fi

{
    echo ">>> $(date)"
    manage_mibios load_data --replicate $SIGNAL || { echo "FAIL exit status $?"; exit 1; }
    echo "+++ ${SECONDS}s"
} | tee -a $LOG
