# Generated by Django 3.2.19 on 2024-10-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncbi_taxonomy', '0002_auto_20230413_1611'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='citation',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='deletednode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='division',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='gencode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='host',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='mergednodes',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='taxname',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='taxnode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='typematerial',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='typematerialtype',
            managers=[
            ],
        ),
    ]
