# Generated by Django 3.2.19 on 2024-10-07 19:08

from django.db import migrations, models
from django.db.models import Prefetch


def fwd(apps, schema_editor):
    """
    Populate the name field with the scientific name
    """
    TaxName = apps.get_model('ncbi_taxonomy', 'TaxName')
    TaxNode = apps.get_model('ncbi_taxonomy', 'TaxNode')
    qs = TaxNode.objects.prefetch_related(Prefetch(
        'taxname_set',
        queryset=TaxName.objects.filter(name_class=TaxName.NAME_CLASS_SCI)
    ))
    for obj in qs:
        obj.name = obj.taxname_set.all()[0].name
    TaxNode.objects.bulk_update(qs, ['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('ncbi_taxonomy', '0002_auto_20230413_1611'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='taxnode',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='taxnode',
            name='name',
            field=models.TextField(default='', verbose_name='scientific name'),
            preserve_default=False,
        ),
        # migrations.RunPython(fwd, migrations.RunPython.noop),
    ]
