# Generated by Django 3.2.18 on 2023-03-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamr', '0002_searchterm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='filt_volume',
            new_name='samp_vol_we_dna_ext',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='secci',
            new_name='secchi',
        ),
        migrations.AddField(
            model_name='sample',
            name='attenuation',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sample',
            name='bluegreen',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sample',
            name='crypto',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sample',
            name='depth_location',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='diatoms',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sample',
            name='gold_analysis_id',
            field=models.TextField(blank=True, default='', max_length=32, verbose_name='GOLD analysis ID'),
        ),
        migrations.AddField(
            model_name='sample',
            name='gold_seq_id',
            field=models.TextField(blank=True, default='', max_length=32, verbose_name='GOLD sequencing project ID'),
        ),
        migrations.AddField(
            model_name='sample',
            name='green_algae',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sample',
            name='h2o2',
            field=models.TextField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='sample',
            name='jgi_biosample',
            field=models.TextField(blank=True, default='', max_length=32, verbose_name='JGI biosample ID'),
        ),
        migrations.AddField(
            model_name='sample',
            name='jgi_study',
            field=models.TextField(blank=True, default='', max_length=32, verbose_name='JGI study ID'),
        ),
        migrations.AddField(
            model_name='sample',
            name='phosphate',
            field=models.TextField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='sample',
            name='phyco_fluoresence',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sample',
            name='silicate',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sample',
            name='sky',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sample',
            name='sortchem',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sample',
            name='tot_microcyst_lcmsms',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sample',
            name='tot_nit',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sample',
            name='transmission',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sample',
            name='wave_height',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sample',
            name='wind_speed',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='bioproject',
            field=models.TextField(blank=True, default='', max_length=32, verbose_name='NCBI BioProject'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='gold_id',
            field=models.TextField(blank=True, default='', max_length=32, verbose_name='GOLD ID'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='jgi_project',
            field=models.TextField(blank=True, default='', max_length=32, verbose_name='JGI Project ID'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='size_fraction',
            field=models.TextField(blank=True, default='', help_text='e.g.: >0.22µm or 0.22-1.6µm', max_length=32, verbose_name='size fraction(s)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='chlorophyl_fluoresence',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='project_id',
            field=models.TextField(blank=True, default='', help_text='Project accession, e.g. NCBI bioproject', max_length=32, verbose_name='NCBI BioProject'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(default='bad_sample_id', help_text='internal sample accession', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.TextField(blank=True, default='', help_text='sample ID or name as given by study', max_length=32),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sra_accession',
            field=models.TextField(blank=True, default='', max_length=16, verbose_name='SRA accession'),
        ),
    ]
