# Generated by Django 3.2.18 on 2023-04-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamr', '0004_search_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='dataset',
            name='private',
            field=models.BooleanField(default=False, help_text='hide this record and related samples from public view'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='metag_pipeline_reg',
            field=models.BooleanField(default=False, help_text='is registered in metagenomic pipeline'),
        ),
    ]
