# Generated by Django 3.2.20 on 2023-10-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamr', '0006_alter_dataset_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='gene_abundance_loaded',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='gene_fasta_loaded',
        ),
        migrations.AddField(
            model_name='sample',
            name='contig_lca_loaded',
            field=models.BooleanField(default=False, help_text='contig LCA data loaded'),
        ),
        migrations.AddField(
            model_name='sample',
            name='gene_alignments_loaded',
            field=models.BooleanField(default=False, help_text='genes loaded via contig_tophit_aln file'),
        ),
    ]
