# Generated by Django 3.2.20 on 2023-10-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamr', '0007_auto_20231019_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='gene_alignment_hits_loaded',
        ),
        migrations.AddField(
            model_name='sample',
            name='gene_abundance_loaded',
            field=models.BooleanField(default=False, help_text='abundance data from contig_tophit_report loaded'),
        ),
        migrations.AddField(
            model_name='sample',
            name='read_abundance_loaded',
            field=models.BooleanField(default=False, help_text='read-based abundance data from tophit_report loaded'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='contig_abundance_loaded',
            field=models.BooleanField(default=False, help_text='contig abundance/rpkm data loaded'),
        ),
    ]
