# Generated by Django 3.2.20 on 2023-11-08 16:29

from django.db import migrations, models
import mibios.models


class Migration(migrations.Migration):

    dependencies = [
        ('glamr', '0008_auto_20231026_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('when_published', models.DateTimeField(null=True, unique=True)),
                ('src_version', models.TextField()),
                ('generation', models.PositiveSmallIntegerField(null=True)),
                ('comment', models.TextField()),
                ('dataset_count', models.PositiveSmallIntegerField()),
                ('sample_count', models.PositiveSmallIntegerField()),
                ('info_uniref', models.TextField(verbose_name='UniRef100')),
                ('info_ncbi_taxonomy', models.TextField(verbose_name='NCBI Taxonomy')),
                ('tool_krona', models.TextField(verbose_name='Krona')),
                ('tool_mmseqs2', models.TextField(verbose_name='MMseqs2')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
    ]
