# Generated by Django 4.2.6 on 2024-01-19 21:06

from django.db import migrations, models
import mibios.models


class Migration(migrations.Migration):
    dependencies = [
        ("glamr", "0010_dbstat_pg_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credit",
            fields=[
                ("id", mibios.models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("version", models.TextField(blank=True, default="")),
                ("date", models.DateField(blank=True, default=None, null=True)),
                ("time", models.TimeField(blank=True, default=None, null=True)),
                (
                    "group",
                    models.CharField(
                        choices=[("S", "reference data sources"), ("T", "other tools")],
                        max_length=1,
                    ),
                ),
                ("url", models.URLField(blank=True, default="")),
                ("comment", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.RemoveField(
            model_name="aboutinfo",
            name="info_ncbi_taxonomy",
        ),
        migrations.RemoveField(
            model_name="aboutinfo",
            name="info_uniref",
        ),
        migrations.RemoveField(
            model_name="aboutinfo",
            name="tool_krona",
        ),
        migrations.RemoveField(
            model_name="aboutinfo",
            name="tool_mmseqs2",
        ),
        migrations.AddConstraint(
            model_name="credit",
            constraint=models.UniqueConstraint(
                fields=("name", "version", "date", "time"), name="credit_uniqueness"
            ),
        ),
        migrations.AddField(
            model_name="aboutinfo",
            name="credits",
            field=models.ManyToManyField(to="glamr.credit"),
        ),
    ]
