# Generated by Django 4.2.6 on 2024-01-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("glamr", "0011_credit_remove_aboutinfo_info_ncbi_taxonomy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutinfo",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="aboutinfo",
            name="when_published",
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
