# Generated by Django 4.2.6 on 2024-01-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("glamr", "0012_alter_aboutinfo_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="amended_site_name",
            field=models.TextField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="sample",
            name="atmospheric_temp",
            field=models.TextField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="sample",
            name="cyano_sonde",
            field=models.TextField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="sample",
            name="env_canada_site",
            field=models.TextField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="sample",
            name="env_kenya_site",
            field=models.TextField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="sample",
            name="nitrite",
            field=models.TextField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="sample",
            name="orp",
            field=models.TextField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="sample",
            name="particulate_cyl",
            field=models.TextField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="sample",
            name="replicate_id",
            field=models.TextField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="sample",
            name="salinity",
            field=models.TextField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="sample",
            name="station_description",
            field=models.TextField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="sample",
            name="total_sonde",
            field=models.TextField(blank=True, default="", max_length=32),
        ),
    ]
