# Generated by Django 4.2.6 on 2024-01-22 22:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("glamr", "0013_sample_amended_site_name_sample_atmospheric_temp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FakeUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name="credit",
            old_name="url",
            new_name="website",
        ),
        migrations.AddField(
            model_name="credit",
            name="paper",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="credit",
            name="source_code",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="credit",
            name="name",
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name="credit",
            name="version",
            field=models.TextField(blank=True, default="", max_length=50),
        ),
    ]
