# Generated by Django 4.2.6 on 2024-01-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("glamr", "0014_fakeuser_rename_url_credit_website_credit_paper_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="group",
            field=models.CharField(
                choices=[("S", "reference data sources"), ("T", "other tools")],
                default="T",
                max_length=1,
            ),
        ),
    ]
