# Generated by Django 4.2.6 on 2024-01-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("glamr", "0015_alter_credit_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="credit",
            options={"ordering": ["name", "version"]},
        ),
        migrations.AlterField(
            model_name="credit",
            name="group",
            field=models.CharField(
                choices=[
                    ("S", "reference data sources"),
                    ("T", "bioinformatics tools"),
                ],
                default="T",
                max_length=1,
            ),
        ),
    ]
