# Generated by Django 3.2.19 on 2024-05-22 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glamr', '0019_alter_sample_sample_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glamr.dataset'),
        ),
        migrations.AddIndex(
            model_name='searchable',
            index=models.Index(fields=['has_hit'], name='glamr_searc_has_hit_fc90ef_idx'),
        ),
    ]
