# Generated by Django 3.2.19 on 2024-07-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glamr', '0020_auto_20240522_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='binning_ok',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='checkm_ok',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='comp_abund_ok',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='contig_fasta_loaded',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='func_abund_ok',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='gene_abundance_loaded',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='genes_ok',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='meta_data_loaded',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='metag_pipeline_reg',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='proteins_ok',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='read_abundance_loaded',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='tax_abund_ok',
        ),
    ]
