# Generated by Django 3.2.19 on 2024-08-01 21:03

from django.db import migrations, models
import mibios.glamr.fields


class Migration(migrations.Migration):

    dependencies = [
        ('glamr', '0021_auto_20240717_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='ammonium',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=8, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='atmospheric_temp',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='attenuation',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='bluegreen',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='calcium',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='chlorophyl',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=7, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='chlorophyl_fluoresence',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='col_dom',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=4, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='conduc',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='crypto',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='cyano_sonde',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='depth_location',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='depth_sediment',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='diatoms',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='diss_org_carb',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='diss_oxygen',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='diss_phos',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ext_anatox',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ext_microcyst',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ext_phyco',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=8, default=None, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='green_algae',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='h2o2',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='latitude',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=8, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='longitude',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=8, default=None, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='magnesium',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='nitrate_nitrite',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=3, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='nitrite',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=4, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='orp',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='par',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='part_microcyst',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=3, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='part_org_carb',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='part_org_nitro',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='particulate_cyl',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='phosphate',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=8, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='phyco_fluoresence',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='potassium',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='salinity',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='samp_vol_we_dna_ext',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='secchi',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='silicate',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=3, default=None, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='size_frac_low',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='size_frac_up',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='suspend_part_matter',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='suspend_vol_solid',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='temp',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='tot_microcyst_lcmsms',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='tot_nit',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=8, default=None, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='total_sonde',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='transmission',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='turbidity',
            field=mibios.glamr.fields.FreeDecimalField(blank=True, decimal_places=3, default=None, max_digits=6, null=True),
        ),
    ]
