# Generated by Django 3.2.19 on 2024-08-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamr', '0022_auto_20240801_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='chlorophyl',
            new_name='chlorophyll',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='chlorophyl_fluoresence',
            new_name='chlorophyll_fluoresence',
        ),
        migrations.AlterField(
            model_name='sample',
            name='gold_analysis_id',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='sample',
            name='gold_seq_id',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='sample',
            name='jgi_biosample',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='sample',
            name='jgi_study',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='sample',
            name='project_id',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.TextField(blank=True, default='', help_text='sample ID or name as given by original data source', max_length=32),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sra_accession',
            field=models.TextField(blank=True, default='', max_length=16),
        ),
    ]
