# Generated by Django 3.2.19 on 2024-11-15 20:40

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamr', '0025_dataset_restricted_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(blank=True, default=None, null=True), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='sample',
            name='access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(blank=True, default=None, null=True), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['access'], name='dataset_access_gin', opclasses=['array_ops']),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=django.contrib.postgres.indexes.GinIndex(fields=['access'], name='sample_access_gin', opclasses=['array_ops']),
        ),
    ]
