# Generated by Django 4.2.15 on 2025-02-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamr', '0026_auto_20241115_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='analysis_dir',
            field=models.TextField(blank=True, default=None, help_text='path to results of analysis, relative to OMICS_PIPELINE_DATA', null=True),
        ),
    ]
