# Generated by Django 4.2.15 on 2025-03-04 21:23

from django.conf import settings
from django.db import migrations

from mibios.omics.tracking import registry as job_registry


class Migration(migrations.Migration):

    dependencies = [
        ('glamr', '0027_alter_sample_analysis_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='contig_abundance_loaded',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='contig_lca_loaded',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='gene_alignments_loaded',
        ),
    ]
