# Generated by Django 4.2.23 on 2025-09-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("glamr", "0028_remove_sample_contig_abundance_loaded_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="amplicon_target",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="analysis_dir",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="fwd_primer",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="gold_analysis_id",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="gold_seq_id",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="has_paired_data",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="read_count",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="reads_mapped_contigs",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="reads_mapped_genes",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="rev_primer",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="sample_type",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="sra_accession",
        ),
    ]
