# Generated by Django 4.2.23 on 2025-09-16 21:58

from django.db import migrations


OLD = 'samp_'
NEW = 'bios_'


def fwd(apps, schema_editor):
    Sample = apps.get_model('glamr', 'Sample')
    for obj in Sample.objects.all():
        if (value := obj.sample_id).startswith(OLD):
            obj.sample_id = NEW + value.removeprefix(OLD)
            obj.full_clean()
            obj.save()
        else:
            raise RuntimeError(f'bad sample_id: {vars(obj)=}')


def rev(apps, schema_editor):
    Sample = apps.get_model('glamr', 'Sample')
    for obj in Sample.objects.all():
        if (value := obj.sample_id).startswith(NEW):
            obj.sample_id = OLD + value.removeprefix(NEW)
            obj.full_clean()
            obj.save()
        else:
            raise RuntimeError(f'bad sample_id: {vars(obj)=}')


class Migration(migrations.Migration):

    dependencies = [
        ("glamr", "0029_sample_model_split"),
    ]

    operations = [migrations.RunPython(fwd, rev)]
