# Generated by Django 4.2.23 on 2025-09-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("glamr", "0030_switch_biosample_id_prefix"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sample",
            options={"default_manager_name": "objects", "verbose_name": "BioSample"},
        ),
    ]
