#!/bin/bash
set -eu
PGBIN=/usr/lib/postgresql/15/bin

echo "Running openshift build: ${OPENSHIFT_BUILD_NAME:-}"
cd "$PGDATA_ROOT"

if [[ -n ${PGDATA_NAME:-} ]]; then
    PGDATA=$PGDATA_ROOT/$PGDATA_NAME
    echo "As provided by runtime environment PGDATA=$PGDATA"
else
    if [[ -L $PGDATA_ROOT/next ]]; then
        # switch to next database generation
        echo "Switching to next database generation..."
        ln -v -sf -T "$(readlink current)" last
        ln -v -sf -T "$(readlink next)" current
    fi

    if [[ -n ${USE_OLD_DATABASE:-} ]]; then
        # use old database
        PGDATA=$(realpath ./last)
        echo "Using old PGDATA=$PGDATA"
    else
        PGDATA=$(realpath ./current)
        echo "Using PGDATA=$PGDATA"
    fi
fi

[[ -d "$PGDATA" ]] || echo "WARNING: not a directory: PGDATA=$PGDATA"

export PGDATA
exec $PGBIN/postgres --config-file=/etc/postgresql/15/main/postgresql.conf
