#!/bin/bash
# Run this script as container lifecycle preStop command.  
set -eu
PGBIN=/usr/lib/postgresql/15/bin

echo "Attempting graceful shutdown..."
cd "$PGDATA_ROOT"
echo -ne "\n$(date) shutdown " >> ../shutdown.log
$PGBIN/pg_ctl stop --wait --timeout=60 --mode=fast
echo -n "[OK]" >> ../shutdown.log
