version: "3"
services:
  apache2:
    image: glamr.apache2
    depends_on:
      - webapp
    restart: always
    ports:
      # port 8080 on host on all interfaces
      - 8080:80
    volumes:
      - static:/glamr/static:ro
  webapp:
    image: glamr.webapp
    depends_on:
      - database
    restart: always
    volumes:
      # manage collectstatic writes here
      - static:/glamr-webapp/static:rw
    environment:
      DJANGO_DEBUG: "false"
      DJANGO_ENABLE_TEST_URLS: "false"
  database:
    image: glamr.database
    restart: always
    shm_size: 1gb
    ports:
      # open port 54321 on all host interfaces
      - 54321:5432
    volumes:
      # permanent storage on host
      - /var/local/postgresql-glamr:/var/local/postgresql

volumes:
  static:
