# Generated by Django 3.2.16 on 2023-02-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0002_auto_20230227_1431'),
        ('ncbi_taxonomy', '0001_initial'),
        ('umrad', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxon',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='ancestors',
        ),
        migrations.RemoveField(
            model_name='uniref100',
            name='taxids',
        ),
        migrations.AddField(
            model_name='uniref100',
            name='taxa',
            field=models.ManyToManyField(related_name='classified_uniref100', to='ncbi_taxonomy.TaxNode'),
        ),
        migrations.DeleteModel(
            name='TaxID',
        ),
        migrations.DeleteModel(
            name='Taxon',
        ),
    ]
