# Generated by Django 3.2.19 on 2024-05-15 20:57

from django.db import migrations, models
import mibios.umrad.fields


class Migration(migrations.Migration):

    dependencies = [
        ('umrad', '0002_auto_20230227_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniref100',
            name='accession',
            field=mibios.umrad.fields.AccessionField(),
        ),
        migrations.AlterField(
            model_name='uniref100',
            name='uniref90',
            field=mibios.umrad.fields.AccessionField(unique=False, verbose_name='UniRef90'),
        ),
        migrations.AddIndex(
            model_name='uniref100',
            index=models.Index(fields=['uniref90'], name='umrad_unire_uniref9_2dfbff_idx'),
        ),
    ]
