# Generated by Django 4.2.28 on 2026-05-04 16:40
# plus manual modifications

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mibios.fields


class Migration(migrations.Migration):

    dependencies = [
        ('umrad', '0003_auto_20240515_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniRef50',
            fields=[
                ('id', mibios.fields.AutoField(primary_key=True, serialize=False)),
                ('accession', models.TextField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='UniRef90',
            fields=[
                ('id', mibios.fields.AutoField(primary_key=True, serialize=False)),
                ('accession', models.TextField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'UniRef90',
                'verbose_name_plural': 'UniRef90',
            },
            managers=[
                ('loader', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='uniref90',
            name='uniref50',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umrad.uniref50'),
        ),
    ]
