# Generated by Django 4.2.28 on 2026-05-04 16:40
# plus manual modifications

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mibios.fields


def fwd(apps, schema_editor):
    """
    Populate new uniref90 table and FK from old char field
    """
    UniRef90 = apps.get_model('umrad', 'UniRef90')
    UniRef100 = apps.get_model('umrad', 'UniRef100')
    print(' Setting UniRef100\'s uniref90 FKs...', end=' ', flush=True)
    # See comment in rev() why Subquery us used.
    subq = UniRef90.loader\
        .filter(accession=models.OuterRef('uniref90_ch')) \
        .values('pk')
    count = UniRef100.loader \
        .exclude(uniref90_ch='') \
        .update(uniref90_id=models.Subquery(subq[:1]))
    print(f'{count} [OK]', end=' ', flush=True)


def rev(apps, schema_editor):
    """
    Re-populate old uniref90 char field from uniref90 table and FK
    """
    UniRef100 = apps.get_model('umrad', 'UniRef100')
    print(' Re-populating uniref90...', end=' ', flush=True)
    # This should be update(uniref_ch=F('uniref90__accession') but update via F
    # across FKs is not supported by Django.  So doing this subquery dance
    # instead:
    subq = UniRef100.loader \
        .filter(pk=models.OuterRef('pk')) \
        .annotate(ur90=models.F('uniref90__accession')) \
        .values('ur90')
    count = UniRef100.loader.exclude(uniref90=None) \
        .update(uniref90_ch=models.Subquery(subq[:1]))
    print(f'{count} [OK]', end=' ', flush=True)


class Migration(migrations.Migration):

    dependencies = [
        ('umrad', '0004_add_uniref50_uniref90_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='uniref100',
            name='umrad_unire_uniref9_2dfbff_idx',
        ),
        migrations.RenameField(
            model_name='uniref100',
            old_name='uniref90',
            new_name='uniref90_ch',
        ),
        migrations.AlterField(
            model_name='uniref100',
            name='uniref90_ch',
            field=mibios.umrad.fields.AccessionField(unique=False, verbose_name='UniRef90', default=''),
        ),
        migrations.AddField(
            model_name='uniref100',
            name='uniref90',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umrad.uniref90'),
        ),
        migrations.RunPython(fwd, rev),
        migrations.RemoveField(
            model_name='uniref100',
            name='uniref90_ch',
        ),
    ]
