# Generated by Django 4.2.28 on 2026-08-20 19:31

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('umrad', '0005_populate_uniref90_FKs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniref50',
            options={'verbose_name': 'UniRef50', 'verbose_name_plural': 'UniRef50'},
        ),
        migrations.AlterModelManagers(
            name='uniref50',
            managers=[
                ('loader', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='uniref100',
            name='uniref90',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='umrad.uniref90'),
        ),
        migrations.AlterField(
            model_name='uniref90',
            name='uniref50',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='umrad.uniref50'),
        ),
    ]
