# Generated by Django 4.2.19 on 2025-04-17 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mibios.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("id", mibios.fields.AutoField(primary_key=True, serialize=False)),
                (
                    "dataset_id",
                    models.PositiveIntegerField(
                        help_text="internal accession to data set/study/project",
                        unique=True,
                    ),
                ),
                (
                    "short_name",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="a short name or description, for internal use, not (necessarily) for public display",
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                ("id", mibios.fields.AutoField(primary_key=True, serialize=False)),
                ("label", models.TextField(max_length=16, unique=True)),
                ("common_name", models.TextField()),
                (
                    "age_years",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("health_state", models.TextField(blank=True, default="")),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                ("id", mibios.fields.AutoField(primary_key=True, serialize=False)),
                (
                    "sample_id",
                    models.CharField(
                        help_text="internal sample accession",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "sample_name",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="sample ID or name as given by original data source",
                        max_length=32,
                    ),
                ),
                (
                    "sample_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("amplicon", "amplicon"),
                            ("metagenome", "metagenome"),
                            ("metatranscriptome", "metatranscriptome"),
                            ("isolate_genome", "isolate_genome"),
                        ],
                        default=None,
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "has_paired_data",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "sra_accession",
                    models.TextField(blank=True, default="", max_length=16),
                ),
                (
                    "amplicon_target",
                    models.TextField(blank=True, default="", max_length=16),
                ),
                ("fwd_primer", models.TextField(blank=True, default="", max_length=32)),
                ("rev_primer", models.TextField(blank=True, default="", max_length=32)),
                (
                    "contig_abundance_loaded",
                    models.BooleanField(
                        default=False, help_text="contig abundance/rpkm data loaded"
                    ),
                ),
                (
                    "contig_lca_loaded",
                    models.BooleanField(
                        default=False, help_text="contig LCA data loaded"
                    ),
                ),
                (
                    "gene_alignments_loaded",
                    models.BooleanField(
                        default=False,
                        help_text="genes loaded via contig_tophit_aln file",
                    ),
                ),
                (
                    "analysis_dir",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="path to results of analysis, relative to OMICS_DATA_ROOT",
                        null=True,
                    ),
                ),
                (
                    "read_count",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="number of read pairs (post-QC) used for assembly mapping",
                        null=True,
                    ),
                ),
                (
                    "reads_mapped_contigs",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="number of reads mapped to contigs",
                        null=True,
                    ),
                ),
                (
                    "reads_mapped_genes",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="number of reads mapped to genes",
                        null=True,
                    ),
                ),
                ("label", models.TextField(max_length=16)),
                ("biosample", models.TextField(blank=True, default="", max_length=16)),
                ("source_material", models.TextField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.OMICS_DATASET_MODEL,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hamb.host"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
