# Generated by Django 4.2.19 on 2025-04-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hamb", "0002_dataset_label_sample_uniq_label_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="control",
            field=models.TextField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="sample",
            name="host",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hamb.host",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="source_material",
            field=models.TextField(max_length=32),
        ),
    ]
