# Generated by Django 3.2.16 on 2023-02-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncbi_taxonomy', '0001_initial'),
        ('omics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contig',
            name='taxid',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='taxid',
        ),
        migrations.AddField(
            model_name='contig',
            name='taxa',
            field=models.ManyToManyField(related_name='classified_contig', to='ncbi_taxonomy.TaxNode'),
        ),
        migrations.AddField(
            model_name='gene',
            name='taxa',
            field=models.ManyToManyField(related_name='classified_gene', to='ncbi_taxonomy.TaxNode'),
        ),
        migrations.AlterField(
            model_name='contig',
            name='lca',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ncbi_taxonomy.taxnode'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='lca',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ncbi_taxonomy.taxnode'),
        ),
        migrations.AlterField(
            model_name='rnacentral',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncbi_taxonomy.taxnode'),
        ),
        migrations.AlterField(
            model_name='taxonabundance',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abundance', to='ncbi_taxonomy.taxnode'),
        ),
    ]
