# Generated by Django 3.2.18 on 2023-04-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0003_auto_20230315_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='tracking_id',
        ),
        migrations.AlterField(
            model_name='sample',
            name='metag_pipeline_reg',
            field=models.BooleanField(default=False, help_text='is registered in metagenomic pipeline'),
        ),
    ]
