# Generated by Django 3.2.20 on 2023-09-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0005_auto_20230413_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contig',
            name='fasta_offset',
            field=models.PositiveBigIntegerField(blank=True, default=None, help_text='offset of first byte of fasta (or similar) header, if there is one, otherwise first byte of sequence', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='fasta_offset',
            field=models.PositiveBigIntegerField(blank=True, default=None, help_text='offset of first byte of fasta (or similar) header, if there is one, otherwise first byte of sequence', null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='fasta_offset',
            field=models.PositiveBigIntegerField(blank=True, default=None, help_text='offset of first byte of fasta (or similar) header, if there is one, otherwise first byte of sequence', null=True),
        ),
    ]
