# Generated by Django 3.2.20 on 2023-10-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0007_auto_20231019_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='length',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gene',
            name='qend',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gene',
            name='send',
            field=models.PositiveIntegerField(),
        ),
    ]
