# Generated by Django 3.2.20 on 2023-10-26 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mibios.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OMICS_SAMPLE_MODEL),
        ('umrad', '0002_auto_20230227_1431'),
        ('omics', '0008_auto_20231023_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneAbundance',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('unique_cov', models.DecimalField(decimal_places=3, max_digits=4)),
                ('target_cov', models.DecimalField(decimal_places=3, max_digits=8)),
                ('avg_ident', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umrad.uniref100')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OMICS_SAMPLE_MODEL)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
                'unique_together': {('sample', 'ref')},
            },
        ),
        migrations.CreateModel(
            name='ReadAbundance',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('unique_cov', models.DecimalField(decimal_places=3, max_digits=4)),
                ('target_cov', models.DecimalField(decimal_places=3, max_digits=8)),
                ('avg_ident', models.DecimalField(decimal_places=3, max_digits=4)),
                ('read_count', models.PositiveIntegerField()),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umrad.uniref100')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OMICS_SAMPLE_MODEL)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
                'unique_together': {('sample', 'ref')},
            },
        ),
        migrations.RemoveField(
            model_name='sample',
            name='gene_alignment_hits_loaded',
        ),
        migrations.AddField(
            model_name='sample',
            name='gene_abundance_loaded',
            field=models.BooleanField(default=False, help_text='abundance data from contig_tophit_report loaded'),
        ),
        migrations.AddField(
            model_name='sample',
            name='read_abundance_loaded',
            field=models.BooleanField(default=False, help_text='read-based abundance data from tophit_report loaded'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='contig_abundance_loaded',
            field=models.BooleanField(default=False, help_text='contig abundance/rpkm data loaded'),
        ),
        migrations.DeleteModel(
            name='Abundance',
        ),
    ]
