# Generated by Django 3.2.20 on 2023-10-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0009_auto_20231026_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneabundance',
            name='target_cov',
            field=models.DecimalField(decimal_places=3, help_text='target coverage alignedResidues / targetLength', max_digits=10),
        ),
        migrations.AlterField(
            model_name='geneabundance',
            name='unique_cov',
            field=models.DecimalField(decimal_places=3, help_text='unique coverage of target uniqueAlignedResidues / targetLength', max_digits=4),
        ),
        migrations.AlterField(
            model_name='readabundance',
            name='read_count',
            field=models.PositiveIntegerField(help_text='number of sequences aligning to target'),
        ),
        migrations.AlterField(
            model_name='readabundance',
            name='target_cov',
            field=models.DecimalField(decimal_places=3, help_text='target coverage alignedResidues / targetLength', max_digits=10),
        ),
        migrations.AlterField(
            model_name='readabundance',
            name='unique_cov',
            field=models.DecimalField(decimal_places=3, help_text='unique coverage of target uniqueAlignedResidues / targetLength', max_digits=4),
        ),
    ]
