# Generated by Django 3.2.20 on 2023-11-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umrad', '0002_auto_20230227_1431'),
        ('omics', '0010_auto_20231030_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readabundance',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abundance', to='umrad.uniref100'),
        ),
        migrations.DeleteModel(
            name='GeneAbundance',
        ),
    ]
