# Generated by Django 3.2.19 on 2024-07-12 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mibios.models
import mibios.omics.models
import mibios.umrad.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OMICS_SAMPLE_MODEL),
        ('omics', '0016_sample_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('path', mibios.umrad.fields.PathField(max_length=200, root=mibios.omics.models.File.get_path_prefix, unique=True)),
                ('public', mibios.umrad.fields.PathField(blank=True, max_length=200, null=True, root=mibios.omics.models.File.get_public_prefix)),
                ('filetype', models.PositiveSmallIntegerField(choices=[(1, 'metagenomic assembly, fasta format'), (2, 'metatranscriptome assembly, fasta format'), (3, 'functional abundance, csv format'), (4, 'taxonomic abundance, csv format'), (5, 'functional abundance (TPM) [csv]')], verbose_name='file type')),
                ('size', models.PositiveBigIntegerField()),
                ('md5sum', models.CharField(blank=True, max_length=32, verbose_name='MD5 sum')),
                ('modtime', models.DateTimeField(verbose_name='modification time')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OMICS_SAMPLE_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('sample', 'filetype'), name='omics_file_sample_ftype_unique'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('public', None), _negated=True), fields=('public',), name='omics_file_public_path_unique'),
        ),
    ]
