# Generated by Django 3.2.19 on 2024-07-19 19:29

from django.db import migrations, models
import mibios.umrad.fields
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0018_auto_20240717_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='readabundance',
            name='rpkm',
            field=models.FloatField(null=True, verbose_name='RPKM'),
        ),
        migrations.AddField(
            model_name='readabundance',
            name='tpm',
            field=models.FloatField(null=True, verbose_name='TPM'),
        ),
        migrations.AlterField(
            model_name='sampletracking',
            name='flag',
            field=models.CharField(choices=[('MD', 'meta data loaded'), ('PL', 'omics pipeline registered'), ('ASM', 'assembly loaded'), ('UAB', 'reads/UR100 abundance loaded'), ('TPM', 'reads/UR100/TPM loaded'), ('TAB', 'taxa abundance loaded')], max_length=3),
        ),
    ]
