# Generated by Django 3.2.19 on 2024-09-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0020_auto_20240719_1618'),
        ('omics', '0020_auto_20240807_1714'),
    ]

    operations = [
    ]
