# Generated by Django 4.2.15 on 2025-02-25 18:59

from django.db import migrations
import mibios.omics.fields
import mibios.omics.storage


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0022_file_field_storage_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_pipeline',
            field=mibios.omics.fields.ReadOnlyFileField(blank=True, default='', storage=mibios.omics.storage.OmicsPipelineStorage(), upload_to=None),
        ),
    ]
