# Generated by Django 4.2.19 on 2025-03-05 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mibios.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OMICS_SAMPLE_MODEL),
        ('omics', '0024_remove_sample_contig_abundance_loaded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', mibios.fields.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=20, unique=True)),
                ('taxon', models.TextField(max_length=100)),
                ('completeness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contamination', models.DecimalField(decimal_places=2, max_digits=5)),
                ('heterogeneity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='strain heterogeneity')),
                ('percent_abund', models.FloatField()),
                ('mean_depth', models.FloatField()),
                ('trimmed_mead_depth', models.FloatField()),
                ('covered_bases', models.IntegerField()),
                ('variance', models.FloatField()),
                ('length', models.IntegerField()),
                ('read_count', models.IntegerField()),
                ('reads_per_base', models.FloatField()),
                ('rpkm', models.FloatField()),
                ('tpm', models.FloatField()),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='binmet93',
            name='checkm',
        ),
        migrations.RemoveField(
            model_name='binmet93',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='binmet97',
            name='checkm',
        ),
        migrations.RemoveField(
            model_name='binmet97',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='binmet99',
            name='checkm',
        ),
        migrations.RemoveField(
            model_name='binmet99',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='contig',
            name='bin_m93',
        ),
        migrations.RemoveField(
            model_name='contig',
            name='bin_m97',
        ),
        migrations.RemoveField(
            model_name='contig',
            name='bin_m99',
        ),
        migrations.RemoveField(
            model_name='contig',
            name='bin_max',
        ),
        migrations.AlterField(
            model_name='file',
            name='filetype',
            field=models.PositiveSmallIntegerField(choices=[(1, 'metagenomic assembly, fasta format'), (2, 'metatranscriptome assembly, fasta format'), (3, 'functional abundance, csv format'), (4, 'taxonomic abundance, csv format'), (5, 'functional abundance (TPM) [csv]'), (6, 'contig abundance [csv]'), (7, 'contig taxonomy [csv]'), (8, 'bin abundance'), (9, 'GTDB Archaea bin classification'), (10, 'GTDB Bacteria bin classification'), (11, 'CheckM results'), (12, 'binning results')], verbose_name='file type'),
        ),
        migrations.DeleteModel(
            name='BinMAX',
        ),
        migrations.DeleteModel(
            name='BinMET93',
        ),
        migrations.DeleteModel(
            name='BinMET97',
        ),
        migrations.DeleteModel(
            name='BinMET99',
        ),
        migrations.DeleteModel(
            name='CheckM',
        ),
        migrations.AddField(
            model_name='bin',
            name='contigs',
            field=models.ManyToManyField(related_name='bins', to='omics.contig'),
        ),
        migrations.AddField(
            model_name='bin',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OMICS_SAMPLE_MODEL),
        ),
    ]
