# Generated by Django 4.2.19 on 2025-03-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0025_bin_redesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletracking',
            name='flag',
            field=models.CharField(choices=[('MD', 'meta data loaded'), ('PL', 'omics pipeline registered'), ('ASM', 'assembly loaded'), ('UAB', 'reads/UR100 abundance loaded'), ('TPM', 'reads/UR100/TPM loaded'), ('TAB', 'taxa abundance loaded'), ('CAB', 'contig abundance loaded'), ('BIN', 'bins loaded')], max_length=3),
        ),
    ]
