# Generated by Django 4.2.21 on 2025-07-18 17:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0026_alter_sampletracking_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bin',
            options={'verbose_name': 'MAG'},
        ),
        migrations.AlterModelManagers(
            name='bin',
            managers=[
                ('loader', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='bin',
            old_name='trimmed_mead_depth',
            new_name='trimmed_mean_depth',
        ),
    ]
