# Generated by Django 4.2.23 on 2025-09-05 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mibios.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OMICS_SAMPLE_MODEL),
        ("omics", "0027_alter_bin_options_alter_bin_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeqSample",
            fields=[
                ("id", mibios.fields.AutoField(primary_key=True, serialize=False)),
                (
                    "sample_id",
                    models.CharField(
                        help_text="internal sample accession",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "sample_name",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="sample ID or name as given by original data source",
                        max_length=32,
                    ),
                ),
                (
                    "sample_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("amplicon", "amplicon"),
                            ("metagenome", "metagenome"),
                            ("metatranscriptome", "metatranscriptome"),
                            ("isolate_genome", "isolate_genome"),
                        ],
                        default=None,
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "has_paired_data",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "sra_accession",
                    models.TextField(blank=True, default="", max_length=16),
                ),
                (
                    "gold_analysis_id",
                    models.TextField(blank=True, default="", max_length=32),
                ),
                (
                    "gold_seq_id",
                    models.TextField(blank=True, default="", max_length=32),
                ),
                (
                    "amplicon_target",
                    models.TextField(blank=True, default="", max_length=16),
                ),
                ("fwd_primer", models.TextField(blank=True, default="", max_length=32)),
                ("rev_primer", models.TextField(blank=True, default="", max_length=32)),
                (
                    "analysis_dir",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="path to results of analysis, relative to OMICS_PIPELINE_DATA",
                        null=True,
                    ),
                ),
                (
                    "read_count",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="number of read pairs (post-QC) used for assembly mapping",
                        null=True,
                    ),
                ),
                (
                    "reads_mapped_contigs",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="number of reads mapped to contigs",
                        null=True,
                    ),
                ),
                (
                    "reads_mapped_genes",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="number of reads mapped to genes",
                        null=True,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.OMICS_SAMPLE_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Dataset",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="amplicon_target",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="analysis_dir",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="dataset",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="fwd_primer",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="has_paired_data",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="read_count",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="reads_mapped_contigs",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="reads_mapped_genes",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="rev_primer",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="sample_id",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="sample_name",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="sample_type",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="sra_accession",
        ),
        migrations.AlterField(
            model_name="gene",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="omics.seqsample"
            ),
        ),
        migrations.AlterField(
            model_name="ncrna",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="omics.seqsample"
            ),
        ),
        migrations.AlterField(
            model_name="readlibrary",
            name="sample",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reads",
                to="omics.seqsample",
            ),
        ),
    ]
