# Generated by Django 4.2.23 on 2025-09-05 18:58
# added datamigration
from functools import partial

from django.db import migrations, models
import django.db.models.deletion


def populate_new_fk(model_name, apps, schema_editor):
    Model = apps.get_model('omics', model_name)
    Sample = apps.get_model('glamr', 'Sample')
    SeqSample = apps.get_model('omics', 'SeqSample')




def reinstate_old_fk(model_name, apps, schema_editor):
    ...


class Migration(migrations.Migration):

    dependencies = [
        ("omics", "0028_sample_model_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="bin",
            name="seq_sample",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="omics.seqsample",
            ),
        ),
        migrations.AddField(
            model_name="compoundabundance",
            name="seq_sample",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="omics.seqsample",
            ),
        ),
        migrations.AddField(
            model_name="contig",
            name="seq_sample",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="omics.seqsample",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="seq_sample",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="omics.seqsample",
            ),
        ),
        migrations.AddField(
            model_name="funcabundance",
            name="seq_sample",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="omics.seqsample",
            ),
        ),
        migrations.AddField(
            model_name="protein",
            name="seq_sample",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="omics.seqsample",
            ),
        ),
        migrations.AddField(
            model_name="readabundance",
            name="seq_sample",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="functional_abundance",
                to="omics.seqsample",
            ),
        ),
        migrations.AddField(
            model_name="sampletracking",
            name="seq_sample",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracking",
                to="omics.seqsample",
            ),
        ),
        migrations.AddField(
            model_name="taxonabundance",
            name="seq_sample",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="omics.seqsample",
            ),
        ),
    ] + [
        RunPython(
            partial(populate_new_fks, model_name),
            partial(reinstante_old_fks, model_name)
        )
        for model_name in (
            'bin', 'compoundabundance', 'contig', 'file', 'funcabundance',
            'protein', 'readabundance', 'sampletracking', 'taxonabundance',
        )
    ]
