# Generated by Django 4.2.23 on 2025-09-05 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("omics", "0028_sample_model_split"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bin",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="omics.seqsample"
            ),
        ),
        migrations.AlterField(
            model_name="compoundabundance",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="omics.seqsample"
            ),
        ),
        migrations.AlterField(
            model_name="contig",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="omics.seqsample"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="omics.seqsample"
            ),
        ),
        migrations.AlterField(
            model_name="funcabundance",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="omics.seqsample"
            ),
        ),
        migrations.AlterField(
            model_name="protein",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="omics.seqsample"
            ),
        ),
        migrations.AlterField(
            model_name="readabundance",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="functional_abundance",
                to="omics.seqsample",
            ),
        ),
        migrations.AlterField(
            model_name="sampletracking",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking",
                to="omics.seqsample",
            ),
        ),
        migrations.AlterField(
            model_name="taxonabundance",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="omics.seqsample"
            ),
        ),
    ]
