# Generated by Django 4.2.23 on 2025-12-05 20:55

from django.db import migrations, models
import django.db.models.deletion
import mibios.fields
import mibios.omics.models


class Migration(migrations.Migration):

    dependencies = [
        ("ncbi_taxonomy", "0004_taxnode_name"),
        ("omics", "0029_sample_model_split_FKs"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmpliconTarget",
            fields=[
                ("id", mibios.fields.AutoField(primary_key=True, serialize=False)),
                (
                    "hmm",
                    models.TextField(
                        help_text="Short name of the HMM model.",
                        max_length=30,
                        verbose_name="HMM name",
                    ),
                ),
                (
                    "tax_group",
                    models.TextField(
                        help_text="Name of the targeted organism or taxonomic group",
                        max_length=30,
                        verbose_name="taxonomic group",
                    ),
                ),
                (
                    "gene",
                    models.TextField(
                        help_text="Common name of the targed gene",
                        max_length=30,
                        verbose_name="target gene name",
                    ),
                ),
                (
                    "start",
                    models.PositiveSmallIntegerField(
                        help_text="Start position of the amplicon target per HMM"
                    ),
                ),
                (
                    "end",
                    models.PositiveSmallIntegerField(
                        help_text="End position of the amplicon target per HMM"
                    ),
                ),
                (
                    "region",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Common name of the targeted variable region(s) if any.",
                        max_length=30,
                        verbose_name="variable region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ASV",
            fields=[
                ("id", mibios.fields.AutoField(primary_key=True, serialize=False)),
                (
                    "accession",
                    models.TextField(
                        blank=True, default="", max_length=12, unique=True
                    ),
                ),
                ("seq", models.TextField(verbose_name="sequence")),
                (
                    "taxon",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ncbi_taxonomy.taxnode",
                        verbose_name="taxonomic classification",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="omics.amplicontarget",
                        verbose_name="target",
                    ),
                ),
            ],
            bases=(mibios.omics.models.IDMixin, models.Model),
        ),
        migrations.RenameField(
            model_name="seqsample",
            old_name="amplicon_target",
            new_name="amplicon_target_label",
        ),
        migrations.AlterField(
            model_name="seqsample",
            name="sra_accession",
            field=models.TextField(
                blank=True, default="", max_length=16, verbose_name="SRA accession"
            ),
        ),
        migrations.CreateModel(
            name="ASVAbundance",
            fields=[
                ("id", mibios.fields.AutoField(primary_key=True, serialize=False)),
                ("count", models.PositiveIntegerField()),
                ("relabund", models.FloatField(verbose_name="relative abundance")),
                (
                    "asv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="omics.asv"
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="omics.seqsample",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="amplicontarget",
            constraint=models.UniqueConstraint(
                models.F("tax_group"),
                models.F("gene"),
                models.F("start"),
                models.F("end"),
                name="uniq_amplicon_target",
            ),
        ),
        migrations.AddField(
            model_name="seqsample",
            name="amplicon_target",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="omics.amplicontarget",
            ),
        ),
        migrations.AddConstraint(
            model_name="asvabundance",
            constraint=models.UniqueConstraint(
                models.F("sample"), models.F("asv"), name="uniq_asv_abund"
            ),
        ),
        migrations.AddConstraint(
            model_name="asv",
            constraint=models.UniqueConstraint(
                models.F("type"), models.F("seq"), name="uniq_asv"
            ),
        ),
        migrations.AddConstraint(
            model_name="asv",
            constraint=models.CheckConstraint(
                check=models.Q(("seq__regex", "^[atgc]+$")), name="sequence_atgc"
            ),
        ),
    ]
