# Generated by Django 4.2.23 on 2025-12-12 22:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("omics", "0030_add_amplicon_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asv",
            options={"verbose_name": "ASV"},
        ),
        migrations.AlterModelOptions(
            name="asvabundance",
            options={"verbose_name": "ASV abundance"},
        ),
        migrations.AlterModelManagers(
            name="asv",
            managers=[
                ("loader", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="asvabundance",
            managers=[
                ("loader", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="amplicontarget",
            name="uniq_amplicon_target",
        ),
        migrations.AddConstraint(
            model_name="amplicontarget",
            constraint=models.UniqueConstraint(
                models.F("hmm"),
                models.F("start"),
                models.F("end"),
                name="uniq_amplicon_target",
            ),
        ),
    ]
