# Generated by Django 4.2.27 on 2026-02-27 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mibios.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OMICS_DATASET_MODEL),
        ('omics', '0032_allow_dataset_based_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetTracking',
            fields=[
                ('id', mibios.fields.AutoField(primary_key=True, serialize=False)),
                ('flag', models.CharField(choices=[('ASM', 'assembly loaded'), ('ASV', 'ASV abundance loaded'), ('BIN', 'bins loaded'), ('CAB', 'contig abundance loaded'), ('MD', 'meta data loaded'), ('PL', 'omics pipeline registered'), ('TAB', 'taxa abundance loaded'), ('UAB', 'reads/UR100 abundance loaded'), ('TPM', 'reads/UR100/TPM loaded')], max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='sampletracking',
            name='uniq_samptrack_flag',
        ),
        migrations.RenameField(
            model_name='sampletracking',
            old_name='sample',
            new_name='subject',
        ),
        migrations.AddConstraint(
            model_name='sampletracking',
            constraint=models.UniqueConstraint(fields=('flag', 'subject'), name='uniq_sampletracking_subject_flag'),
        ),
        migrations.AddField(
            model_name='datasettracking',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to=settings.OMICS_DATASET_MODEL),
        ),
        migrations.AddConstraint(
            model_name='datasettracking',
            constraint=models.UniqueConstraint(fields=('flag', 'subject'), name='uniq_datasettracking_subject_flag'),
        ),
    ]
