# Generated by Django 4.2.28 on 2026-03-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0034_file_location_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqsample',
            name='analysis_dir',
            field=models.TextField(blank=True, default=None, help_text="path to results of analysis, relative to OMICS_PIPELINE_DATA / 'omics'", null=True),
        ),
        migrations.AlterField(
            model_name='seqsample',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('amplicon', 'amplicon'), ('metagenome', 'metagenome'), ('metatranscriptome', 'metatranscriptome'), ('isolate_genome', 'isolate_genome'), ('metabolome', 'metabolome')], default=None, max_length=32, null=True),
        ),
    ]
