# Generated by Django 4.2.28 on 2026-05-01 15:27

from django.db import migrations, models
import django.db.models.deletion
import mibios.fields


class Migration(migrations.Migration):

    dependencies = [
        ('umrad', '0003_auto_20240515_1657'),
        ('omics', '0035_alter_two_seqsample_field_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcabundance',
            options={'default_manager_name': 'objects', 'verbose_name': 'function abundance'},
        ),
        migrations.RemoveField(
            model_name='funcabundance',
            name='rpkm',
        ),
        migrations.RemoveField(
            model_name='funcabundance',
            name='scos',
        ),
        migrations.AddField(
            model_name='funcabundance',
            name='sum_rpkm',
            field=models.FloatField(null=True, verbose_name='RPKM'),
        ),
        migrations.AddField(
            model_name='funcabundance',
            name='sum_tpm',
            field=models.FloatField(null=True, verbose_name='TPM'),
        ),
        migrations.AlterField(
            model_name='datasettracking',
            name='flag',
            field=models.CharField(choices=[('ASM', 'assembly loaded'), ('ASV', 'ASV abundance loaded'), ('BIN', 'bins loaded'), ('CAB', 'contig abundance loaded'), ('FAB', 'fn name abundance loaded'), ('FXA', 'fn xref abundance loaded'), ('MD', 'meta data loaded'), ('PL', 'omics pipeline registered'), ('TAB', 'taxa abundance loaded'), ('UAB', 'reads/UR100 abundance loaded'), ('TPM', 'reads/UR100/TPM loaded')], max_length=3),
        ),
        migrations.AlterField(
            model_name='funcabundance',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_abundance', to='omics.seqsample'),
        ),
        migrations.AlterField(
            model_name='sampletracking',
            name='flag',
            field=models.CharField(choices=[('ASM', 'assembly loaded'), ('ASV', 'ASV abundance loaded'), ('BIN', 'bins loaded'), ('CAB', 'contig abundance loaded'), ('FAB', 'fn name abundance loaded'), ('FXA', 'fn xref abundance loaded'), ('MD', 'meta data loaded'), ('PL', 'omics pipeline registered'), ('TAB', 'taxa abundance loaded'), ('UAB', 'reads/UR100 abundance loaded'), ('TPM', 'reads/UR100/TPM loaded')], max_length=3),
        ),
        migrations.CreateModel(
            name='FunctionNameAbundance',
            fields=[
                ('id', mibios.fields.AutoField(primary_key=True, serialize=False)),
                ('sum_tpm', models.FloatField(null=True, verbose_name='TPM')),
                ('sum_rpkm', models.FloatField(null=True, verbose_name='RPKM')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abundance', to='umrad.functionname', verbose_name='function name')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_name_abundance', to='omics.seqsample')),
            ],
            options={
                'verbose_name': 'function name abundance',
                'abstract': False,
                'default_manager_name': 'objects',
                'unique_together': {('sample', 'name')},
            },
        ),
    ]
