# Generated by Django 4.2.28 on 2026-05-07 18:21

from django.db import migrations, models
import django.db.models.deletion
import mibios.fields


class Migration(migrations.Migration):

    dependencies = [
        ('umrad', '0005_populate_uniref90_FKs'),
        ('omics', '0036_add_function_abundance_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasettracking',
            name='flag',
            field=models.CharField(choices=[('ASM', 'assembly loaded'), ('ASV', 'ASV abundance loaded'), ('BIN', 'bins loaded'), ('CAB', 'contig abundance loaded'), ('FAB', 'fn name abundance loaded'), ('FXA', 'fn xref abundance loaded'), ('MD', 'meta data loaded'), ('PL', 'omics pipeline registered'), ('TAB', 'taxa abundance loaded'), ('UAB', 'reads/UR100 abundance loaded'), ('TPM', 'reads/UR100/TPM loaded'), ('U9A', 'UR90 abundance loaded')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sampletracking',
            name='flag',
            field=models.CharField(choices=[('ASM', 'assembly loaded'), ('ASV', 'ASV abundance loaded'), ('BIN', 'bins loaded'), ('CAB', 'contig abundance loaded'), ('FAB', 'fn name abundance loaded'), ('FXA', 'fn xref abundance loaded'), ('MD', 'meta data loaded'), ('PL', 'omics pipeline registered'), ('TAB', 'taxa abundance loaded'), ('UAB', 'reads/UR100 abundance loaded'), ('TPM', 'reads/UR100/TPM loaded'), ('U9A', 'UR90 abundance loaded')], max_length=3),
        ),
        migrations.CreateModel(
            name='UniRef90Abundance',
            fields=[
                ('id', mibios.fields.AutoField(primary_key=True, serialize=False)),
                ('sum_tpm', models.FloatField(null=True, verbose_name='TPM')),
                ('sum_rpkm', models.FloatField(null=True, verbose_name='RPKM')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abundance', to='umrad.uniref90')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniref90_abundance', to='omics.seqsample')),
            ],
            options={
                'verbose_name': 'UniRef90 abundance',
                'abstract': False,
                'default_manager_name': 'objects',
                'unique_together': {('sample', 'ref')},
            },
        ),
    ]
