# Generated by Django 4.2.28 on 2026-08-20 19:31

from django.db import migrations, models
import django.db.models.deletion
import mibios.fields


class Migration(migrations.Migration):

    dependencies = [
        ('umrad', '0006_several_uniref_clustering_bits'),
        ('omics', '0037_uniref90abundance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seqsample',
            options={'verbose_name': 'assay'},
        ),
        migrations.AlterField(
            model_name='seqsample',
            name='amplicon_target',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='omics.amplicontarget', verbose_name='Amplicon target (ASV type)'),
        ),
        migrations.CreateModel(
            name='UniRef50Abundance',
            fields=[
                ('id', mibios.fields.AutoField(primary_key=True, serialize=False)),
                ('sum_tpm', models.FloatField(null=True, verbose_name='TPM')),
                ('sum_rpkm', models.FloatField(null=True, verbose_name='RPKM')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abundance', to='umrad.uniref50')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniref50_abundance', to='omics.seqsample')),
            ],
            options={
                'verbose_name': 'UniRef50 abundance',
                'abstract': False,
                'default_manager_name': 'objects',
                'unique_together': {('sample', 'ref')},
            },
        ),
    ]
