# Generated by Django 4.2.28 on 2026-08-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0038_UniRef50Abundance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniref90abundance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
