# Generated by Django 4.2.28 on 2026-08-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0039_alter_uniref90abundance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contig',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='readabundance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uniref50abundance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
